version: '3.1'
services:
  apache:
    build: apache
    volumes:
      - "${APACHEVOLUME}"
    ports:
      - ${PROJECT_HTTP_PORT}:80
      - ${PROJECT_HTTPS_PORT}:443
    expose:
      - "${PROJECT_HTTP_PORT}"
    dns:
      - 192.168.1.5
    restart: always
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_UPSTREAM=${VIRTUAL_UPSTREAM}
      - MAGE_RUN_CODE=${MAGE_RUN_CODE}
      - MAGE_RUN_TYPE=${MAGE_RUN_TYPE}
  memcached:
    image: memcached
    expose:
      - 11211
  rediscache:
    image: redis
    expose:
      - 6379
  redisfpc:
    image: redis
    expose:
      - 6379
  mail:
    image: schickling/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080
  ext_tunnel:
    image: gtriggiano/ngrok-tunnel
    ports:
      - 4040
    environment:
      - TARGET_HOST=apache
      - TARGET_PORT=80
  mysql:
      image: mysql:5.5
      environment:
        MYSQL_ROOT_PASSWORD: magento
        MYSQL_USER: magento
        MYSQL_PASSWORD: magento
        MYSQL_DATABASE: magento
      ports:
        - "3307:3306"
      volumes:
        - ${MYSQLVOLUME}
        - ./db/magento.sql:/docker-entrypoint-initdb.d/dump.sql
      restart: always
